"""
This type stub file was generated by pyright.
"""

import typing
from ..schemas.match_strategy import MatchStrategy

"""
This module contains a FastAPI dependency that can be used to validate that a user
has a certain permission before accessing a path
"""
log = ...
class CheckPermissions:
    """
    This class can be used as FastAPI dependency to check if a user has
    the required permissions to access a path
    """
    def __init__(self, required_permission: typing.Union[str, typing.List[str]], match_strategy: MatchStrategy = ...) -> None:
        """
        Initialize the dependency. The required permission can be a single string
        or a list of strings. The match strategy can be either AND or OR, meaning
        that all permissions must be present or at least one permission must be present.

        :param required_permission: _description_
        :type required_permission: typing.Union[str, typing.List[str]]
        :param match_strategy: _description_, defaults to MatchStrategy.AND
        :type match_strategy: MatchStrategy, optional
        """
        ...
    
    def __call__(self, user=..., auth: typing.List[str] = ...): # -> AuthorizationResult:
        ...
    


