"""
This type stub file was generated by pyright.
"""

from fastapi import Request

"""
This module contains a helper function that can be used as FastAPI dependency
to easily retrieve the resolved permissions for the user
"""
async def get_auth(request: Request): # -> list[str] | Any | None:
    """
    This function can be used as FastAPI dependency
    to easily retrieve the user object
    """
    ...

