---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# Taskfile for managing development tasks in a multi-platform environment

version: "3"

env:
  PYTHONPYCACHEPREFIX: ".cache/pycache"

tasks:
  all:
    desc: Run all unit + integration tests
    cmds:
      - poetry run pytest -v --tb=short
    silent: true

  unit:
    desc: Run unit tests only
    cmds:
      - poetry run pytest -m unit
    silent: true

  int:
    desc: Run integration tests only
    cmds:
      - poetry run pytest -v -m integration
    silent: true

  watch:
    desc: Watch and rerun tests on change (requires ptw)
    cmds:
      - poetry run ptw -- --tb=short -v
    silent: true

  settings:
    desc: Run settings tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/core/test_settings.py --tb=short
    silent: true

  health:
    desc: Run health tests
    cmds:
      - poetry run pytest -m health --tb=short
    silent: true

  health:service:
    desc: Run health service tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/services/test_health_service.py --tb=short
    silent: true

  health:dao:
    desc: Run health DAO tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/db/test_health_dao.py --tb=short
    silent: true

  health:repository:
    desc: Run health repository tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/db/test_health_repository.py --tb=short
    silent: true

  health:api:
    desc: Run health API tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/api/test_health_api.py --tb=short
    silent: true

  messages:service:
    desc: Run messages service tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/services/test_messages_service.py --tb=short
    silent: true

  messages:dao:
    desc: Run messages DAO tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/db/test_messages_dao.py --tb=short
    silent: true

  messages:repository:
    desc: Run messages repository tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/db/test_messages_repository.py --tb=short
    silent: true

  messages:api:
    desc: Run messages API tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/api/test_messages_api.py --tb=short
    silent: true

  profile:api:
    desc: Run profile API tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/api/test_profile_api.py --tb=short
    silent: true

  mapstate:
    desc: Run map state tests
    cmds:
      - poetry run pytest -m map_states --tb=short
    silent: true

  mapstate:service:
    desc: Run map state service tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/services/test_map_states_service.py --tb=short
    silent: true

  mapstate:dao:
    desc: Run map state DAO tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/db/test_map_states_dao.py --tb=short
    silent: true

  mapstate:repository:
    desc: Run map state repository tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/db/test_map_states_repository.py --tb=short
    silent: true

  mapstate:api:
    desc: Run map state API tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/api/test_map_states_api.py --tb=short
    silent: true

  utils:license:
    desc: Run license utility tests
    cmds:
      - poetry run pytest {{.ROOT_DIR}}/tests/utils/test_licenses.py --tb=short
    silent: true
