"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel

"""
Pydantic schema used to represent an exception response.
"""
class ExceptionResponse(BaseModel):
    """
    Schema used to describe an exception response
    """
    detail: str | None = ...


