"""
This type stub file was generated by pyright.
"""

import typing
from starlette.authentication import BaseUser

"""
This module contains a base user implementation

It is mainly used if the user does not provide a custom function to retrieve
the user based on the token claims
"""
class FastApiUser(BaseUser):
    """Sample API User that gives basic functionality"""
    def __init__(self, first_name: str, last_name: str, user_id: typing.Any) -> None:
        """
        FastAPIUser Constructor
        """
        ...
    
    @property
    def is_authenticated(self) -> bool:
        """
        Checks if the user is authenticated. This method essentially does nothing,
        but it could implement session logic for example.
        """
        ...
    
    @property
    def display_name(self) -> str:
        """Display name of the user"""
        ...
    
    @property
    def identity(self) -> str:
        """Identification attribute of the user"""
        ...
    


