"""
This type stub file was generated by pyright.
"""

import typing
from starlette.authentication import AuthenticationBackend, BaseUser
from starlette.requests import HTTPConnection
from fastapi_keycloak_middleware.schemas.keycloak_configuration import KeycloakConfiguration

"""
This module contains the Keycloak backend.

It is used by the middleware to perform the actual authentication.
"""
log = ...
class KeycloakBackend(AuthenticationBackend):
    """
    Backend to perform authentication using Keycloak
    """
    def __init__(self, keycloak_configuration: KeycloakConfiguration, user_mapper: typing.Callable[[typing.Dict[str, typing.Any]], typing.Awaitable[typing.Any]] | None) -> None:
        ...
    
    async def authenticate(self, conn: HTTPConnection) -> tuple[list[str], BaseUser | None]:
        """
        The authenticate method is invoked each time a route is called that
        the middleware is applied to.
        """
        ...
    


